CREATE TABLE ACCOUNTS (
    ID INTEGER NOT NULL PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(32) NOT NULL,
    COMPLETE_NAME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_ACCOUNTS START WITH 1 
INCREMENT BY 1;

INSERT INTO ACCOUNTS (ID, EMAIL, PASSWORD, COMPLETE_NAME) VALUES
(
    SEQ_ACCOUNTS.NEXTVAL,
    'luis@puccampinas.edu.br',
    'luis',
    'Luis Silva'
);

COMMIT;

SELECT * FROM ACCOUNTS;