CREATE TABLE BETS (
    ID INTERGER NOT NULL PRIMARY KEY,
    valor INTEGER NOT NULL,
    eventoID INTEGER,
    accountsID INTEGER,
    FOREIGN KEY (eventoID) REFERENCES EVENTS(ID),
    FOREIGN KEY (accountsID) REFERENCES ACCOUNTS(ID)
);

INSERT INTO BETS (ID, VALOR, EVENTOID, ACCOUNTSID) VALUES 
(
    SEQ_ACCOUNTS.NEXTVAL,
    30,
    82,
    83
); 
