CREATE TABLE BETS (
    ID INTERGER NOT NULL PRIMARY KEY,
    valor INTEGER NOT NULL,
    eventoID INTEGER,
    accountsID INTEGER,
    FOREIGN KEY (eventoID) REFERENCES EVENTS(ID),
    FOREIGN KEY (accountsID) REFERENCES ACCOUNTS(ID)
);