CREATE TABLE BETS (
    ID INTERGER NOT NULL PRIMARY KEY,
    valor INTEGER NOT NULL,
    eventoID INTEGER,
    accountsID INTEGER,
    FOREIGN KEY (eventoID) REFERENCES EVENTS(ID),
    FOREIGN KEY (accountsID) REFERENCES ACCOUNTS(ID)
);

INSERT INTO BETS (ID, VALOR, EVENTOID, ACCOUNTSID) VALUES 
(
    SEQ_ACCOUNTS.NEXTVAL,
    30,
    82,
    83
); 

ALTER TABLE BETS
ADD choice NUMBER(1);

ALTER TABLE BETS
MODIFY choice DEFAULT 0;

ALTER TABLE BETS
ADD CONSTRAINT choice_check CHECK (choice IN (0, 1));
