ALTER TABLE EVENTS ADD FK_ID_CATEGORY INTEGER;

ALTER TABLE EVENTS
ADD CONSTRAINT FK_ID_CATEGORY FOREIGN KEY (FK_ID_CATEGORY) REFERENCES CATEGORY (ID_CATEGORY);

SELECT C.ID_CATEGORY AS "id", C.NOME AS "nome", COUNT(E.ID) AS "qtdEventos"
FROM CATEGORY C
    JOIN EVENTS E ON E.FK_ID_CATEGORY = C.ID_CATEGORY
GROUP BY
    C.ID_CATEGORY,
    C.NOME